### ISSUE TITLE
Issue in training on custom data-set

### ISSUE THREAD

**Issue by mrin9san** [CompVis/taming-transformers#106]
Hi, I am trying to train the network using a custom mri dataset for which I have followed the points mentioned as

1. install the repo with `conda env create -f environment.yaml, conda activate taming` `pip install -e`  -- **Done**
2. put your .jpg files in a folder `your_folder` -- **Created a folder inside `/taming-transformers/data` as `mri `and put .png images.**
3. create 2 text files a `xx_train.txt` and `xx_test.txt` that point to the files in your training and test set respectively (for example `find $(pwd)/your_folder -name "*.jpg" > train.txt)` -- **created two text files with entries with like `filename.png`. Changed the `custom_vqgan.yaml` line entries as 
`training_images_list_file: /taming-transformers/data/mri/try-test.txt`
`test_images_list_file: /home/shiva/taming-transformers/data/mri/try-test.txt`**
4. run python main.py --base configs/custom_vqgan.yaml -t True --gpus 0,1 to train on two GPUs. Use --gpus 0, (with a trailing comma) to train on a single GPU -- **Well following issues are encountered -**

```
Traceback (most recent call last):
  File "main.py", line 562, in <module>
    trainer.fit(model, data)
  File "/home/shiva/anaconda3/envs/taming/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 445, in fit
    results = self.accelerator_backend.train()
  File "/home/shiva/anaconda3/envs/taming/lib/python3.8/site-packages/pytorch_lightning/accelerators/cpu_accelerator.py", line 59, in train
    results = self.train_or_test()
  File "/home/shiva/anaconda3/envs/taming/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 66, in train_or_test
    results = self.trainer.train()
  File "/home/shiva/anaconda3/envs/taming/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 467, in train
    self.run_sanity_check(self.get_model())
  File "/home/shiva/anaconda3/envs/taming/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 659, in run_sanity_check
    _, eval_results = self.run_evaluation(test_mode=False, max_batches=self.num_sanity_val_batches)
  File "/home/shiva/anaconda3/envs/taming/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 567, in run_evaluation
    for batch_idx, batch in enumerate(dataloader):
  File "/home/shiva/anaconda3/envs/taming/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/shiva/anaconda3/envs/taming/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/shiva/anaconda3/envs/taming/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/shiva/anaconda3/envs/taming/lib/python3.8/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/shiva/anaconda3/envs/taming/lib/python3.8/site-packages/PIL/Image.py", line 2972, in open
    fp.seek(0)
AttributeError: 'str' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/shiva/anaconda3/envs/taming/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/shiva/anaconda3/envs/taming/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/shiva/anaconda3/envs/taming/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/shiva/taming-transformers/taming/data/custom.py", line 18, in __getitem__
    example = self.data[i]
  File "/home/shiva/taming-transformers/taming/data/base.py", line 56, in __getitem__
    example["image"] = self.preprocess_image(self.labels["file_path_"][i])
  File "/home/shiva/taming-transformers/taming/data/base.py", line 46, in preprocess_image
    image = Image.open(image_path)
  File "/home/shiva/anaconda3/envs/taming/lib/python3.8/site-packages/PIL/Image.py", line 2974, in open
    fp = io.BytesIO(fp.read())
AttributeError: 'str' object has no attribute 'read'
```
Please give suggestions as to what may go wrong. Also do I have to give complete file path of the images inside the text file?

**Comment by mrin9san** [comment]
Well, figured out whats wrong and training going good on my custom dataset. It was a silly new line cursor that I inserted in the text file at the bottom.
