### ISSUE TITLE
pytorch_lightning.utilities.exceptions.MisconfigurationException: You called `self.log(val/rec_loss, ...)` twice in `validation_step` with different arguments. This is not allowed

### ISSUE THREAD

**Issue by mwzhu** [CompVis/taming-transformers#134]
I am trying to train on custom data in Google Colab, I got this error:

Traceback (most recent call last):
  File "/content/taming-transformers/main.py", line 566, in <module>
    trainer.fit(model, data)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 730, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 680, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 766, in _fit_impl
    results = self._run(model, ckpt_path=ckpt_path)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 1170, in _run
    results = self._run_stage()
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 1255, in _run_stage
    return self._run_train()
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 1279, in _run_train
    self._run_sanity_check()
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 1347, in _run_sanity_check
    val_loop.run()
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/base.py", line 191, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 119, in advance
    dataloader, dataloader_idx if self.num_dataloaders > 1 else None, dl_max_batches
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/base.py", line 191, in run
    self.advance(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 129, in advance
    output = self._evaluation_step(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 227, in _evaluation_step
    output = self.trainer._call_strategy_hook("validation_step", *kwargs.values())
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/trainer.py", line 1664, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/strategies/strategy.py", line 338, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/content/taming-transformers/taming/models/vqgan.py", line 117, in validation_step
    self.log_dict(log_dict_ae)
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/core/lightning.py", line 488, in log_dict
    rank_zero_only=rank_zero_only,
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/core/lightning.py", line 427, in log
    rank_zero_only=rank_zero_only,
  File "/usr/local/lib/python3.7/dist-packages/pytorch_lightning/trainer/connectors/logger_connector/result.py", line 484, in log
    f"You called `self.log({name}, ...)` twice in `{fx}` with different arguments. This is not allowed"
pytorch_lightning.utilities.exceptions.MisconfigurationException: You called `self.log(val/rec_loss, ...)` twice in `validation_step` with different arguments. This is not allowed

**Comment by ivopascal** [comment]
I ran into this issue as well. The solution for me was to update the "size"s to match the number of images in train/test. 

I think the idea is that this is done automatically, but seems to fail for some reason. This might help get you on your way regardless.

**Comment by ivopascal** [comment]
Ran into this issue as well, and it was because I didn't have the right versions of some dependencies installed. Fixed it with
```
!pip install pytorch-lightning==1.0.8
!pip install torch==1.7.0 torchvision==0.8.1 torchtext==0.8.0
```

**Comment by basusattwik** [comment]
Hi, what was the solution to this problem? I am seeing the same issue while trying to train on custom data.
