### ISSUE TITLE
pip._internal.vcs.versioncontrol.RemoteNotFoundError

### ISSUE THREAD

**Issue by tianjun318** [CompVis/taming-transformers#199]
during install clip

(ldm) tianye@DESKTOP-OPEU24M:/mnt/e/program/Dreambooth-Stable-Diffusion$ pip install -e git+https://github.com/openai/CLIP.git@main#egg=clip
Obtaining clip from git+https://github.com/openai/CLIP.git@main#egg=clip
ERROR: Exception:
Traceback (most recent call last):
  File "/home/tianye/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'clip'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tianye/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/vcs/git.py", line 322, in get_remote_url
    found_remote = remotes[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tianye/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
    status = self.run(options, args)
  File "/home/tianye/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/home/tianye/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 320, in run
    requirement_set = resolver.resolve(
  File "/home/tianye/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/home/tianye/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 445, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/tianye/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 310, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/home/tianye/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/home/tianye/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 79, in from_requirement
    cands = build_iter_view(provider.find_matches([requirement]))
  File "/home/tianye/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_vendor/resolvelib/structs.py", line 148, in build_iter_view
    matches = list(matches)
  File "/home/tianye/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 255, in <genexpr>
    if constraint.is_satisfied_by(c)
  File "/home/tianye/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/base.py", line 66, in is_satisfied_by
    return self.specifier.contains(candidate.version, prereleases=True)
  File "/home/tianye/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 194, in version
    self._version = self.dist.parsed_version
  File "/home/tianye/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 239, in dist
    self._prepare()
  File "/home/tianye/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 226, in _prepare
    dist = self._prepare_distribution()
  File "/home/tianye/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 346, in _prepare_distribution
    return self._factory.preparer.prepare_editable_requirement(self._ireq)
  File "/home/tianye/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 573, in prepare_editable_requirement
    req.update_editable(self.download_dir is None)
  File "/home/tianye/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 655, in update_editable
    vcs_backend.obtain(self.source_dir, url=hidden_url)
  File "/home/tianye/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/vcs/versioncontrol.py", line 654, in obtain
    existing_url = self.get_remote_url(dest)
  File "/home/tianye/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/vcs/git.py", line 324, in get_remote_url
    raise RemoteNotFoundError
pip._internal.vcs.versioncontrol.RemoteNotFoundError
(ldm) tianye@DESKTOP-OPEU24M:/mnt/e/program/Dreambooth-Stable-Diffusion$

**Comment by hzphzp** [comment]
same problem

**Comment by sulong8** [comment]
So did you solve the problem?
