### ISSUE TITLE
error on train resume

### ISSUE THREAD

**Issue by ink1** [CompVis/taming-transformers#45]
I am getting the error below on train resume. Say,
`python main.py --base configs/pic.yaml -t True --gpus 0, --max_epochs 2 --resume logs/2021-05-01T01-34-57_pic`
Oddly enough, it seems to work fine when I retry.

> Traceback (most recent call last):
  File "main.py", line 562, in <module>
    trainer.fit(model, data)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/trainer.py", line 445, in fit
    results = self.accelerator_backend.train()
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 148, in train
    results = self.ddp_train(process_idx=self.task_idx, model=model)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 279, in ddp_train
    self.trainer.train_loop.setup_training(model)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/training_loop.py", line 174, in setup_training
    self.trainer.checkpoint_connector.restore_weights(model)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 75, in restore_weights
    self.restore(self.trainer.resume_from_checkpoint, on_gpu=self.trainer.on_gpu)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 107, in restore
    self.restore_model_state(model, checkpoint)
  File "/usr/local/lib/python3.6/dist-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 128, in restore_model_state
    model.load_state_dict(checkpoint['state_dict'])
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 1052, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Net2NetTransformer:
	Unexpected key(s) in state_dict: "cond_stage_model.colorize".

**Comment by pesser** [comment]
You could try adding `colorize_nlabels=<nlabels>` to the `params` section of the `cond_stage_model` config where `<nlabels>` is the number of classes in your segmentation maps (182 for sflckr and 183 for coco and 151 for ade20k). Alternatively resume via `model.params.ckpt_path=logs/2021-05-01T01-34-57_pic/checkpoints/last.ckpt` instead of the `--resume` flag, then it will load the weights non-strictly.
